# The R script the app generates must parse, run on its own, and give the app's
# results exactly. It is built from structured records of what the user did, so
# these tests drive a session through shiny::testServer() and then run what
# comes out.

q <- function(expr) suppressWarnings(suppressMessages(expr))
DIMS5 <- c("mo", "sc", "ua", "pd", "ad")

# A session: load, map, validate, two value columns, five analyses.
run_session <- function(e, source = c("example", "csv"), path = NULL) {
  source <- match.arg(source)
  rv <- shiny::reactiveValues(raw_data = NULL, mapping = NULL,
                              processed_data = NULL, results = list(),
                              load_example = 0L, value_cols = character(0L),
                              steps = list())

  q(shiny::testServer(e$mod_data_server, args = list(rv = rv), {
    if (source == "example") {
      session$setInputs(use_example = 1)
    } else {
      session$setInputs(file = list(name = basename(path), datapath = path))
    }
    session$setInputs(version = "3L", col_mo = "mo", col_sc = "sc",
                      col_ua = "ua", col_pd = "pd", col_ad = "ad",
                      col_fu = "time", col_groupvar = "procedure",
                      col_id = "id", col_vas = "vas", col_age = "ageband",
                      col_sex = "gender", col_utility = "",
                      fu_order = c("Pre-op", "Post-op"), confirm = 1)
  }))
  q(shiny::testServer(e$mod_validation_server, args = list(rv = rv), {
    session$setInputs(proceed = 1)
  }))
  q(shiny::testServer(e$mod_values_server, args = list(rv = rv), {
    session$setInputs(method = "direct", country = "GB",
                      col_name = "utility", add = 1)
    session$setInputs(method = "uk", age_col = "ageband", age_kind = "bands",
                      sex_col = "gender", male_value = "Male",
                      col_name = "eq5d_uk_5L", add = 1)
  }))
  for (o in list(c("profile", "111"), c("vas", "21"),
                 c("values", "31"), c("profile", "121fig"),
                 c("profile", "141"))) {
    q(shiny::testServer(e$mod_analysis_server, args = list(rv = rv), {
      session$setInputs(component = o[1])
      session$setInputs(output = o[2])
      if (o[2] == "31") session$setInputs(utility_col = "utility")
      session$setInputs(run = 1)
    }))
  }
  shiny::isolate(list(steps = rv$steps, results = rv$results,
                      data = rv$processed_data))
}

generate <- function(session)
  eq5dsuite:::script_from_session(session$steps, session$results)

# Run a generated script in a clean environment.
run_script <- function(lines, data_path = NULL) {
  f <- tempfile(fileext = ".R")
  if (!is.null(data_path))
    lines <- fill_data_path(lines, data_path)
  writeLines(lines, f)
  env <- new.env(parent = globalenv())
  # The script prints its plots; send them nowhere rather than leaving an
  # Rplots.pdf behind in the check directory.
  grDevices::pdf(NULL)
  on.exit(grDevices::dev.off(), add = TRUE)
  q(sys.source(f, envir = env))
  env
}

# ---------------------------------------------------------------------------
# The script itself
# ---------------------------------------------------------------------------

test_that("the generated script parses", {
  skip_unless_app()
  lines <- generate(run_session(app_env()))
  expect_silent(parse(text = paste(lines, collapse = "\n")))
})

test_that("it has a header and the four sections, in order", {
  skip_unless_app()
  lines <- generate(run_session(app_env()))
  txt <- paste(lines, collapse = "\n")

  expect_match(txt, "Generated by the eq5dsuite Shiny app on \\d{4}-\\d{2}-\\d{2}")
  expect_match(txt, "eq5dsuite 2\\.", fixed = FALSE)
  expect_match(txt, R.version.string, fixed = TRUE)
  expect_match(txt, "library(eq5dsuite)", fixed = TRUE)

  at <- vapply(c("# 1. Load data", "# 2. Validation",
                 "# 3. EQ-5D value calculation", "# 4. Analysis"),
               function(h) grep(h, lines, fixed = TRUE)[1], integer(1L))
  expect_false(anyNA(at))
  expect_identical(at, sort(at))
})

test_that("it uses only exported functions, and defines its own helpers", {
  skip_unless_app()
  lines <- generate(run_session(app_env()))
  expect_false(any(grepl(":::", lines, fixed = TRUE)))

  pd <- utils::getParseData(parse(text = paste(lines, collapse = "\n"),
                                  keep.source = TRUE))
  called <- unique(pd$text[pd$token == "SYMBOL_FUNCTION_CALL"])

  # Every eq5dsuite function it calls is exported. The app's own supporting
  # functions are internal, so this is what makes the script write their work
  # out instead of calling them: naming one here would fail this.
  ours <- grep("^eq5d|^eqxw|^eqvs|^make_|^toEQ5D", called, value = TRUE)
  expect_true(all(ours %in% getNamespaceExports("eq5dsuite")),
              info = paste(setdiff(ours, getNamespaceExports("eq5dsuite")),
                           collapse = ", "))

  # The one helper it writes out for itself is defined before it is used.
  # band_midpoint() is gone: the age bands are now resolved when the script
  # is generated and written out as a lookup, so the script holds the ages
  # the app actually used rather than a second copy of the parser.
  defined <- grep("^format_eq5d_table <- function", lines)
  expect_length(defined, 1L)
  expect_true(all(grep("\\bformat_eq5d_table\\(", lines) > defined))
  expect_false(any(grepl("band_midpoint", lines, fixed = TRUE)))
  # The lookup is there instead, and its labels are quoted so it parses.
  expect_true(any(grepl("age_for_band <- c(", lines, fixed = TRUE)))
})

test_that("it mentions no app objects", {
  skip_unless_app()
  lines <- generate(run_session(app_env()))
  for (bad in c("rv$", "input$", "session$", "reactive", "processed_data"))
    expect_false(any(grepl(bad, lines, fixed = TRUE)), info = bad)
})

# ---------------------------------------------------------------------------
# Running it, on example_data
# ---------------------------------------------------------------------------

test_that("running the script reproduces the app's values and results", {
  skip_unless_app()
  e <- app_env()
  session <- run_session(e)
  env <- run_script(generate(session))

  # The value columns, to the last bit.
  expect_identical(env$analysis_data$utility, session$data$utility)
  expect_identical(env$analysis_data$eq5d_uk_5L, session$data$eq5d_uk_5L)

  # Every saved result.
  objs <- eq5dsuite:::.result_object_names(session$results)
  for (i in seq_along(session$results)) {
    r <- session$results[[i]]
    got <- env[[objs[i]]]
    if (identical(r$result_type, "plot")) {
      # The app saves the ggplot object itself, so compare the data it carries
      # and the layers drawn from it.
      expect_s3_class(got$p, "ggplot")
      expect_equal(got$p$data, r$plot$data, info = r$label)
      expect_equal(length(got$p$layers), length(r$plot$layers), info = r$label)
      expect_equal(got$p$labels, r$plot$labels, info = r$label)
    } else {
      expect_equal(got, r$data, info = r$label)
      # And the formatted copy the script prints. The script formats the table
      # itself rather than calling into the package, so this is what keeps the
      # two from drifting: percentages, counts and headings must all match
      # what the app showed.
      expect_equal(env[[paste0(objs[i], "_formatted")]],
                   eq5dsuite:::eq5d_format_table(r$data), info = r$label)
    }
  }
})

test_that("the script uses the same ages as the app (F15)", {
  skip_unless_app()
  # The script carries the label -> age table the app resolved, rather than a
  # second copy of the band parser, so this compares mapped values and not
  # intermediate strings.
  e <- app_env()
  session <- run_session(e)
  env <- run_script(generate(session))
  expect_identical(env$analysis_data$eq5d_uk_5L, session$data$eq5d_uk_5L)
  expect_false(all(is.na(env$analysis_data$eq5d_uk_5L)))
  lines <- generate(session)
  expect_true(any(grepl("age_for_band <- c(", lines, fixed = TRUE)))
  expect_false(any(grepl("band_midpoint", lines, fixed = TRUE)))
})

test_that("the objects are named after their analysis", {
  skip_unless_app()
  e <- app_env()
  session <- run_session(e)
  env <- run_script(generate(session))

  expect_true(all(c("profile_level_summary", "vas_summary", "utility_summary",
                    "profile_pchc_by_group_plot") %in% ls(env)))
  # Tables keep both the raw and the formatted result.
  expect_true("profile_level_summary_formatted" %in% ls(env))
  expect_s3_class(env$profile_level_summary, "data.frame")
  expect_true(all(vapply(env$profile_level_summary_formatted, is.character,
                         logical(1L))))
})

# The script's validation section, on its own, so it can be run against data
# chosen to trip a particular check. Everything between the two section
# headings; `lines` is the generated script.
validation_block <- function(lines) {
  at <- grep("^# [0-9]+\\. ", lines)
  from <- grep("^# 2\\. Validation", lines)
  to <- at[at > from][1L]
  lines[seq(from + 1L, (if (is.na(to)) length(lines) + 1L else to) - 1L)]
}

# Run that block over `df` and say what it signalled: "error", "warning" or
# "clean". The script checks the data it is given, so the block needs only
# `analysis_data` and the mapping it was generated from.
validation_outcome <- function(lines, df, mapping) {
  env <- new.env(parent = globalenv())
  # The script's preamble first: it defines parse_number() and
  # parse_levels(), which the checks use.
  pre <- lines[seq_len(grep("^# 1\\. Load data", lines)[1L] - 1L)]
  eval(parse(text = paste(pre, collapse = "\n")), envir = env)
  env$analysis_data <- df
  env$mapping <- mapping
  code <- parse(text = paste(validation_block(lines), collapse = "\n"))
  warned <- FALSE
  out <- tryCatch(
    withCallingHandlers(
      { suppressMessages(for (ex in code) eval(ex, envir = env)); "clean" },
      warning = function(w) { warned <<- TRUE; invokeRestart("muffleWarning") }),
    error = function(e) "error")
  if (identical(out, "error")) "error" else if (warned) "warning" else "clean"
}

test_that("the script's checks signal what eq5d_validate signals", {
  skip_unless_app()
  e <- app_env()
  session <- run_session(e)
  lines <- generate(session)
  mapping <- eq5dsuite:::.step_of(session$steps, "map")$mapping
  df <- session$data

  # example_data carries the 9 and 999 missing codes, which are out of the
  # dimensions' range, so there is something to warn about and nothing to stop
  # for. A naive stopifnot() would halt the script here, where the app went on.
  found <- q(eq5dsuite:::eq5d_validate(df, mapping, quiet = TRUE))
  expect_true(any(found$type == "warning"))
  expect_false(any(found$type == "error"))
  expect_identical(validation_outcome(lines, df, mapping), "warning")

  # A missing dimension column is the one finding that stops the script.
  gone <- df[, setdiff(names(df), "mo"), drop = FALSE]
  missing_found <- q(eq5dsuite:::eq5d_validate(gone, mapping, quiet = TRUE))
  expect_true(any(missing_found$type == "error"))
  expect_identical(validation_outcome(lines, gone, mapping), "error")

  # Clean data pass without a warning: levels in range, EQ VAS in range, and
  # one row per patient and timepoint.
  ok <- data.frame(
    mo = 1L, sc = 2L, ua = 1L, pd = 3L, ad = 1L,
    id = 1:4, fu = rep(c("Pre-op", "Post-op"), 2L), vas = c(50, 60, 70, 80))
  expect_identical(validation_outcome(lines, ok, mapping), "clean")
})

test_that("a repeated analysis gets numbered object names", {
  results <- list(
    list(call = list(fn = "eq5d_profile_level_summary")),
    list(call = list(fn = "eq5d_vas_summary")),
    list(call = list(fn = "eq5d_profile_level_summary")))
  expect_equal(eq5dsuite:::.result_object_names(results),
               c("profile_level_summary_1", "vas_summary",
                 "profile_level_summary_2"))
})

# ---------------------------------------------------------------------------
# Running it, on a CSV
# ---------------------------------------------------------------------------

test_that("a script for an uploaded CSV runs on that file", {
  skip_unless_app()
  e <- app_env()

  path <- withr::local_tempfile(fileext = ".csv")
  utils::write.csv(eq5dsuite::example_data, path, row.names = FALSE)

  session <- run_session(e, source = "csv", path = path)
  lines <- generate(session)

  # The script names the file and leaves the path to be filled in.
  expect_true(any(grepl(basename(path), lines, fixed = TRUE)))
  expect_true(any(grepl('data_path <- "REPLACE BY ACTUAL PATH"', lines,
                        fixed = TRUE)))
  # The reading is written out, with its options, so it can be changed. The
  # script calls read.csv() itself rather than anything of the package's.
  pd <- utils::getParseData(parse(text = paste(lines, collapse = "\n"),
                                  keep.source = TRUE))
  expect_true("read.csv" %in% pd$text[pd$token == "SYMBOL_FUNCTION_CALL"])
  expect_true(any(grepl('sep = ","', lines, fixed = TRUE)))
  expect_true(any(grepl("check.names = FALSE", lines, fixed = TRUE)))

  env <- run_script(lines, data_path = path)
  expect_identical(env$analysis_data$utility, session$data$utility)
  expect_equal(env$profile_level_summary, session$results[[1L]]$data)
})

# ---------------------------------------------------------------------------
# Ordering, removal, and safe quoting
# ---------------------------------------------------------------------------

test_that("the script follows the Results order and drops what was removed", {
  skip_unless_app()
  e <- app_env()
  session <- run_session(e)

  rv <- shiny::reactiveValues(results = session$results)
  shiny::isolate({
    e$move_result(rv, session$results[[4L]]$id, -1L)
    e$move_result(rv, session$results[[4L]]$id, -1L)
    e$remove_result(rv, session$results[[2L]]$id)
  })
  kept <- shiny::isolate(rv$results)

  lines <- eq5dsuite:::script_from_session(session$steps, kept)
  labels <- vapply(kept, function(r) r$label, character(1L))
  at <- vapply(labels, function(l) grep(l, lines, fixed = TRUE)[1], integer(1L))
  expect_false(anyNA(at))
  expect_identical(at, sort(at))              # same order as the Results page
  # The removed one is gone.
  expect_false(any(grepl(session$results[[2L]]$label, lines, fixed = TRUE)))
})

test_that("values a user typed are quoted safely", {
  odd_file <- 'od"d name\\.csv'
  odd_dims <- c("It's mo", 'a"b', "c\\d", "pd", "ad")
  steps <- list(
    list(kind = "load", source = "file", file = odd_file,
         ext = "csv", read_args = list(sep = ";")),
    list(kind = "map", mapping = list(
      eq5d_version = "3L",
      names_eq5d = odd_dims,
      name_groupvar = "group with spaces", name_fu = NULL)))
  results <- list(list(
    label = "odd", result_type = "table",
    call = list(fn = "eq5d_profile_level_summary", type = "table",
                args = list(names_eq5d = odd_dims[1:2],
                            levels_fu = c("Pre\"op", "Post'op")))))

  lines <- eq5dsuite:::script_from_session(steps, results)

  # The real test: it is still valid R.
  exprs <- parse(text = paste(lines, collapse = "\n"))
  expect_gt(length(exprs), 0L)

  # And the values survive the round trip unchanged. Find the assignment by
  # walking the parsed expressions, not by slicing lines.
  assigned <- function(name) {
    at <- Filter(function(e)
      is.call(e) && identical(as.character(e[[1L]]), "<-") &&
        identical(as.character(e[[2L]]), name), as.list(exprs))
    expect_length(at, 1L)
    eval(at[[1L]][[3L]])
  }

  # The column names the user chose are written into the script as data, so
  # a quote or a backslash in one cannot change what the script does.
  mapped <- assigned("mapped")
  expect_identical(mapped[1:5], odd_dims)
  expect_true("group with spaces" %in% mapped)
  # And each is renamed to what the analysis functions expect.
  expect_identical(assigned("as_named")[1:5],
                   c("mo", "sc", "ua", "pd", "ad"))
  expect_identical(length(mapped), length(assigned("as_named")))
  # The file name, quote and backslash and all, is written as R source.
  expect_true(any(grepl(deparse(odd_file), lines, fixed = TRUE)))
})

test_that("an empty session still produces a readable script", {
  lines <- eq5dsuite:::script_from_session(list(), list())
  expect_silent(parse(text = paste(lines, collapse = "\n")))
  expect_true(any(grepl("No data were loaded", lines, fixed = TRUE)))
  expect_true(any(grepl("No analyses were saved", lines, fixed = TRUE)))
})

# ---------------------------------------------------------------------------
# The download
# ---------------------------------------------------------------------------

test_that("the Export page offers the script and previews it", {
  skip_unless_app()
  e <- app_env()
  session <- run_session(e)
  rv <- shiny::reactiveValues(results = session$results, steps = session$steps)

  shiny::testServer(e$mod_export_server, args = list(rv = rv), {
    session$flushReact()
    path <- output$download_script
    expect_match(basename(path), "^eq5d_analysis_\\d{8}\\.R$")
    expect_silent(parse(path))

    preview <- output$script_preview
    expect_match(preview, "# 4. Analysis", fixed = TRUE)
  })
})
